var test2 = {
  '单选题': [
    'B 1.(单选)以下为主控式创新(Dominant lnnovation)的创新关系图(Relationship Mapping)，请问右下 角的圆圈是() A.成本 B.价值 C.品牌 D.速度 E.价格',
    'A 2.(单选)承上题，请问哪个是所谓的“蛋黄”() A.产品 B.使用者 C.成本 D.价值 E.品牌',
    'D 3.(单选)CPS 第一层为智能感应层(Connection)，其目的为() A.系统的动态优化与协同执行 B.对目标的识别与决策优化 C.隐性问题显性化 D.统一有效的数据环境 E.镜像建模与数据挖掘',
    'E 4.(单选)CPS 第三层为智能网络层(Cyber)，其目的为() A.系统的动态优化与协同执行 B.对目标的识别与决策优化 C.隐性问题显性化 D.统一有效的数据环境 E.镜像建模与数据挖掘',
    'B 5.(单选)依照 IMS 提出的技术开发流程，包含1健康评估、2信号处理、3可用寿命预测、4 故障诊断、5特征提取，请问正确的流程为() A.43125 B.25143 C.45213 D.23514 E.25413',
    'C 6.(单选)生产力管理模式五个层次中，我们现在正进行哪一层次() A.5S & Kaizen B.Lean & 6Sigma C.Predictive Tools D.Optimization E.Autonomous',
    'D 7.(单选)CPS 系统要建立的 M 是() A.Method B.Measurement C.Maintenance D.Models E.Machine',
    'D 8.(单选)CPS 最重要的目的为实现() A.制造 B.自造 C.智造 D.传承 E.模型',
    'D 9.(单选)工业数据分析的核心是() A.大数据分析(Big Data) B.自动化机器人(Autonomous Robot) C.人工智慧(Artificial Intelligence) D.故障检测与健康管理(Prognostics and Health Management) E.感测器(Sensor)',
    'C 10.(单选)工业大数据分析并不仅仅依靠演算法工具，而是更加注重() A.统计上的关联性 B.边缘计算能力 C.逻辑清晰的分析流程和与分析流程相匹配 D.云端平台计算能力 E.建立模型的共通性',
    'E 11.(单选)预测型制造的核心技术是() A.一个云平台 B.一个快捷的边缘计算 C.一个快速 3D 打样平台 D.一个资料搜集平台 E.一个包含智慧软体进行预测建模的智慧计算工具',
    'A 12.(单选)工业 4.0 是以_____为主导的第四次工业革命() A.智能制造 B.个性化定制 C.机器人自动化生产 D.3D 制造 E.工业云',
    'C 13.(单选) 20 世纪 70 年代日本曾经提出以“全生产系统维护(TPM)”的提出零停机、零废 品、零事故、_____的“4 零”目标() A.零库存 B.零排放 C.零效率损失 D.零人工 E.零误差',
    'B 14.(单选)煎蛋模型的目标是() A.核心产品 B.创值 C.客户满意度 D.产品功能 E.产品竞争力',
    'C 15.(单选)大数据分析可以分为 Descriptive、Prescriptive、______ 三种型式() A.Connection B.Analysis C.Predictive D.Comparison E.Control',
    'C 16.(单选)大数据分析主要有 Descriptive、Prescriptive、______ 三种型式() A.Connection B.Analysis C.Predictive D.Comparison E.Control',
    'A 17.(单选)______的核心就在于注重产品技术开发到注重顾客价值创造的思维转变过程，实现从 创新到创值() A.主控式创新思维 B.持续性创新思维 C.破坏式创新思维 D.跨越性创新思维 E.架构性创新思维',
    'E 18.(单选)在数据分析过程中，从问题的产生到数据分析，要先做好数据的______() A.分类、分解、分析 B.分类、分割、分析 C.分辨、分割、分解 D.分辨、分类、分解 E.分类、分割、分解',
    'C 19.(单选)工业人工智能(Industrial AI)是一种实现人工智能在工程应用的系统训练及方法，具 有快速性(speed)，系统性(systematic)外，还具有什么特性() A.标准性(Standard) B.安全性(Security) C.可传承性(Sustainable) D.服务性(Service) E.特殊性(Specifieness)',
    'B 20.(单选)工业大数据的意义包括数据的来源，________，数据的意义() A.数据的冗余 B.数据的关系 C.数据的多样 D.数据的时效 E.数据的维度',
    'E 21.(单选)大数据的 6 个 C 系统不包括() A.连接 B.云端技术 C.虚拟网络 D.社群 E.标准化的内容',
    'C 22.(单选)在带锯案例中，带锯使用的全生命信息分类错误的是() A.工况类:工件信息 B.特征类:振动信号 C.工况类:质量参数 D.状态类:健康状态结果 E.状态类:故障模式',
    'D 23.(单选)在带锯案例中，哪些不是全生命周期预测分析过程() A.从特征提取聚类 B.每个聚类集群下的预测与决策 C.特征与磨损阶段的映射 D.对带锯特征多加感应器 E.设备状态特征聚类分析',
  ],
  '多选题': [
    'ABD 24.(多选)Time-machine 是一种应用于对离散事件之间的关系性建构分析的方法，它的特性包括 哪些() A.离散性 B.方向性 C.普适性 D.时序性 E.安全性',
    'AD 25.(多选)智慧维护技术设计和开发流程七步骤包含需求定义、分析模型选择、部署策略和实 验设计、解决方案可行性分析和选择、专案开发和实践，请问缺少的两步是() A.监控层次定义 B.团队组织编制 C.绩效考核制度 D.数据获取计划 E.绩效获取计划',
    'BD 26.(多选)数据采集时可以考量的六种类数据，除了环境数据(温、湿度等)、工况信息(生产 设定参数:进给、转速等)、系统集成(MES、ERP 等)、工作状态(传感信号:震动、电流等) 以外，还有什么() A.自动化规划 B.绩效数据 C.财务信息 D.维护维修记录 E.监控规划',
    'ABC 27.(多选)特征提取方法大类分为哪几类() A.时域 B.频域 C.时频域 D.间域 E.标域',
    'ABE 28.(多选)以下属于数据合适性分析的有() A.分类分割 B.分解分析 C.分红分利 D.分工分力 E.分享分忧',
    'ABCE 29.(多选)关键有效的大数据可以从以下哪些途径得到() A.感应器，控制器 B.关系的量测 C.历史记录 D.图纸标识 E.参数',
    'ABDE 30.(多选)工业人工智能的机会在于() A.需要解决的问题 B.需要预测的问题 C.单调及肮脏环境的问题 D.需要避免的问题 E.不可见的问题',
    'ABC 31.(多选)工业大数据技术核心是为解决哪 3B 问题 () A.Broken B.Bad Quality C.Below Surface D.Bandwidth E.Bankruptcy',
    'BCE 32.(多选)李杰教授在《工业大数据》中提到的“蛋黄”/“蛋白”理论中“蛋黄”除了 Machine (机器)、Methods(工艺)、Measurement(测量)以外，还有哪些() A.Market(市场) B.Material(材料) C.Maintenance(维护) D.Manufacturing(制造) E.Modeling(建模)',
    'BCDE 33.(多选)李杰教授在《工业大数据》中提到的“蛋黄”/“蛋白”理论中“蛋白”除 Connection (连接)、Cloud(云)、Cyber(虚拟网络)以外，还有哪些() A.Control(控制) B.Content/Context(数据内容与来源背景) C.Community (社群) D.Customization(定制化) E.Communication(沟通)',
    'ABDE 34.(多选)CPS 技术的应用，设备需具备哪些能力() A.自我预测(Self-Predict) B.自我比较(Self-Compare) C.自我分析(Self-Analysis) D.自动察觉(Self-Aware) E.自我配置(Self-Configure)',
    'ACD 35.(多选)大数据具有 4V 的特征，除了包括量(Volume)外，还具备哪些() A.速度(Velocity) B.有效的(Valid) C.多样性(Variety) D.真实性(Veracity) E.大量的(Vast)',
    'ABCDE 36.(多选)工业数据除具有更强的专业性外，还有哪些特点() A.关联性 B.目的性 C.时序性 D.解析性 E.流程性',
    'ABCDE 37.(多选)对于工业 4.0 的智慧制造转型而言，工业大数据的核心价值目标是什么() A.将产品功能与用户需求相结合 B.将客制化与规模化结合 C.个性化与大众化结合 D.微观与宏观结合 E.现在与未来结合',
    'ABCDE 38.(多选)工业 4.0 环境下的 CPS 技术体系架构，包括了哪几个层次的建构模式() A.智能感知层 B.资讯挖掘层 C.网路层 D.认知层 E.配置层',
    'ABCDE 39.(多选)网络层的主要功能包括以下哪几种() A.连接(Connection) B.通信(Communication) C.计算(Computation) D.比较(Comparison) E.控制(Control)',
    'ABCDE 40.(多选)生产力管理模式中，包括以下哪几种模式() A.发送模式 B.精密与 6 Sigma 模式 C.预测分析模式 D.决策管理优化模式 E.启动协会优化模式',
    'ABCDE 41.(多选)使用工业人工智能工具(Industrial AI Tools)在每一个场域，主要包括以下哪几种() A.速度(Speed) B.及时性(Timeliness) C.精度(Precisian) D.复杂性(Complexity) E.不确定性(Uncertaincy)',
    'BCD 42.(多选)CPS 以多种数据的建模为基础，以智能连接(Connection)，智能分析(Conversion)， 及_______的 5C 体系等主要架构() A.智能检测(Check) B.智能网路(Cyber) C.智能认知(Cognition) D.智能配置执行(Configuration) E.智能传送(Carry)',
    'BDE 43.(多选)集团强调工业互联网为目前发展最重要的核心，其中六流包含三虚、三实，三虚包 含下列哪三流() A.人流 B.讯流 C.物流 D.金流 E.技术流',
    'ACE 44.(多选)集团强调工业互联网为目前发展最重要的核心，其中六流包含三虚、三实，三实包 含下列哪三流() A.人流 B.金流 C.物流 D.讯流 E.过程流',
    'ABE 45.(多选)以下哪些是预后推估的流程阶段() A.Clustering B.Selection of Baseline and Critical Units C.End-to-End modeling D.Classification E.Peer-to-Peer Comparison',
    'BE 46.(多选)以下哪些不在局部缺陷评估的典型流程中() A.Signal Processing and Feature Extraction B.Data Augmentation C.Fault Localization D.Fault Type Identification E.Resource Assessment',
    'BCD 47.(多选)在 Nissan 机器人健康联网系统里，包含了哪些必要组件() A.搜寻引擎 B.服务器 C.整合制造系统 D.数据库 E.JTAG',
  ],
  '判断题': [
    'O 48.(判断)依据数据是否有标签可将建模分析方法分为监督式学习与非监督式学习()',
    'X 49.(判断)有个榔头什么都能敲，有了 AI 什么都能解决()',
    'O 50.(判断)使用 CPS 及高端数据处理是因为数据量大及多类()',
    'X 51.(判断)推动中国制造的技术创新、模式创新和服务创新，中国企业面临的最大挑战是将增 长重点从“蛋白”向内转到“蛋黄”上()',
    'O 52.(判断)智能制造系统运行的逻辑是:发生问题→分析问题(模型)→模型调整 5 个要素→ 解决问题→模型积累经验，并分析问题的根源→模型调整 5 个要素→避免问题()',
    'O 53.(判断)一个制造系统是否能够被称为智能，主要判断其是否具备以下两个特征:(1)是否 能够学习人的经验，从而替代人来分析问题和形成决策;(2)能否从新的问题中积累经验，从而 避免问题的再次发生()',
    'O 54.(判断)有别于互联网大数据，工业大数据的分析技术核心要解决的问题是 Below Surface、 Broken、Bad Quality ()',
    'X 55.(判断)大数据与智能制造三个重要元素之间的关系是数据->问题->知识(模型)()',
    'O 56.(判断)创值就是客户欣赏你的产品，愿意花时间购买，这样你的未来才是美好的()',
    'O 57.(判断)在工业 4.0 中，大数据逻辑应该有两个 V，一是可见性(Visibility)，即透过大数据分 析使以往未见的重要因素和资讯变得可见，二是价值(Value)，即透过大数据分析所得到的资讯 应该被转换成价值()',
    'X 58.(判断)对于零组件或是设备的健康衰退评估可以用 CV 值(Confidence Value)来表达:CV 是一个 0~1 之间的无因次量，1 代表衰退到不可接受的状态，0 代表健康状态(又称健康基线状 态)()',
    'X 59.(判断)在[煎蛋模型]理论，“蛋白”是核心产品，而“蛋黄”则是真正为客户创造价值的创 新服务，是能让企业持续性获利的关键()',
    'O 60.(判断)在工业大数据中提到，企业的创新模式包括，持续性创新(Continuous Innovation)， 跨越性创新(Discontinuous Innovation)及主控式创新三种()',
    'O 61.(判断)主控式创新工具，可以包括:创新矩阵(Innovation Matrix)、生产者、产品与服务关 系三角圈(Relationship Map)、应用地图(Application Space Mapping)()',
    'O 62.(判断)连网数据收集要做到全方位设备数据，主要包括:环境参数、系统整合、绩效数据、 维护保养记录、工作状态数据、状态资讯六个项目()',
    'X 63.(判断)固定周期下的固定特征分析(FCFT)及自使用性资料获取而设计，仅限用于具备常 规固定运行模式及事件激励的运行模式()',
    'O 64.(判断)特征(Features)是从原始数据中提取的精炼信息(Compact information extracted from raw data)()',
    'O 65.(判断)维护技术的发展包括:Reactive Maintenance、 Preventive Maintenance、Condition-Based Maintenance、 Prognostics and Health Management()',
    'O 66.(判断)集团互联网就是云移物大智网+机器人()',
    'O 67.(判断)新工业革命环境下的中国制造模式转型方式是推动“智慧的参与者”、“智慧的制 造”和“智慧的产品”三者的协调互联 ()',
    'O 68.(判断)CPS 以 5C 体系为架构，5C 可以指智能连接 Connection、智能分析 Conversion、智能 网路 Cyber、智能认知 Cognition 和智能配置与执行 Configuration()',
    'X 69.(判断)CPS 的广义内涵，是实体系统(Physical System)中的比较性(Comparison)、关系性 (Correlation)和一致性(Consistency)的对称性分析、预测、优化和管理()',
  ],
};
